"""Game constants and configuration."""

# Game settings
MIN_PLAYERS = 3
MAX_PLAYERS = 12

# Game state cleanup
GAME_TTL_SECONDS = 3600  # Games are cleaned up after 1 hour

# WebSocket settings
WEBSOCKET_PING_INTERVAL = 30  # Ping every 30 seconds

# Word pairs for the game
# Format: (villager_word, knight_word)
# Villagers get the first word, Knights get the similar but different second word
WORD_PAIRS = [
    # Animals
    ("tiger", "lion"),
    ("elephant", "mammoth"),
    ("giraffe", "llama"),
    ("penguin", "puffin"),
    ("dolphin", "whale"),
    ("butterfly", "moth"),
    ("kangaroo", "wallaby"),
    ("octopus", "squid"),
    ("peacock", "parrot"),
    ("hamster", "guinea pig"),
    ("eagle", "hawk"),
    ("rabbit", "hare"),
    ("monkey", "ape"),
    ("panda", "koala"),
    ("shark", "barracuda"),

    # Objects
    ("telescope", "binoculars"),
    ("umbrella", "parasol"),
    ("guitar", "ukulele"),
    ("camera", "camcorder"),
    ("keyboard", "piano"),
    ("bicycle", "tricycle"),
    ("lighthouse", "watchtower"),
    ("compass", "GPS"),
    ("mirror", "reflection"),
    ("clock", "watch"),
    ("scissors", "shears"),
    ("laptop", "tablet"),
    ("backpack", "suitcase"),
    ("wallet", "purse"),
    ("sunglasses", "goggles"),

    # Places
    ("museum", "gallery"),
    ("library", "bookstore"),
    ("restaurant", "cafe"),
    ("airport", "heliport"),
    ("hospital", "clinic"),
    ("stadium", "arena"),
    ("theater", "cinema"),
    ("beach", "shore"),
    ("mountain", "hill"),
    ("forest", "jungle"),
    ("desert", "wasteland"),
    ("volcano", "geyser"),
    ("waterfall", "fountain"),
    ("castle", "fortress"),
    ("temple", "shrine"),

    # Food & Drink
    ("pizza", "flatbread"),
    ("sushi", "sashimi"),
    ("chocolate", "cocoa"),
    ("coffee", "espresso"),
    ("sandwich", "panini"),
    ("burger", "slider"),
    ("pasta", "noodles"),
    ("icecream", "gelato"),
    ("pancake", "waffle"),
    ("muffin", "cupcake"),
    ("cookie", "biscuit"),
    ("salad", "coleslaw"),
    ("soup", "stew"),
    ("cheese", "yogurt"),
    ("bread", "toast"),

    # Activities
    ("swimming", "diving"),
    ("dancing", "ballet"),
    ("painting", "drawing"),
    ("reading", "studying"),
    ("cooking", "baking"),
    ("singing", "humming"),
    ("hiking", "trekking"),
    ("fishing", "angling"),
    ("camping", "glamping"),
    ("skiing", "snowboarding"),
    ("surfing", "paddleboarding"),
    ("juggling", "circus"),
    ("gardening", "landscaping"),
    ("knitting", "crocheting"),
    ("writing", "typing"),

    # Weather & Nature
    ("rainbow", "aurora"),
    ("thunder", "lightning"),
    ("sunrise", "sunset"),
    ("snowflake", "hailstone"),
    ("breeze", "wind"),
    ("hurricane", "typhoon"),
    ("tornado", "cyclone"),
    ("earthquake", "tremor"),
    ("meteor", "comet"),
    ("eclipse", "solstice"),

    # Transportation
    ("airplane", "jet"),
    ("submarine", "U-boat"),
    ("helicopter", "chopper"),
    ("spaceship", "rocket"),
    ("motorcycle", "scooter"),
    ("sailboat", "yacht"),
    ("train", "locomotive"),
    ("car", "automobile"),
    ("bus", "coach"),
    ("balloon", "blimp"),

    # Sports
    ("basketball", "netball"),
    ("soccer", "football"),
    ("tennis", "badminton"),
    ("baseball", "cricket"),
    ("volleyball", "handball"),
    ("bowling", "curling"),
    ("boxing", "wrestling"),
    ("archery", "darts"),
    ("fencing", "swordplay"),
    ("hockey", "lacrosse"),

    # Professions
    ("teacher", "professor"),
    ("doctor", "surgeon"),
    ("chef", "cook"),
    ("pilot", "aviator"),
    ("astronaut", "cosmonaut"),
    ("detective", "investigator"),
    ("firefighter", "paramedic"),
    ("scientist", "researcher"),
    ("artist", "painter"),
    ("musician", "composer"),

    # Household Items
    ("refrigerator", "freezer"),
    ("microwave", "oven"),
    ("toaster", "grill"),
    ("blender", "mixer"),
    ("vacuum", "broom"),
    ("television", "monitor"),
    ("pillow", "cushion"),
    ("blanket", "duvet"),
    ("curtain", "blinds"),
    ("lamp", "chandelier"),

    # Colors
    ("crimson", "scarlet"),
    ("azure", "cobalt"),
    ("violet", "purple"),
    ("amber", "gold"),
    ("emerald", "jade"),
    ("navy", "indigo"),
    ("coral", "salmon"),
    ("turquoise", "cyan"),
    ("burgundy", "maroon"),
    ("ivory", "cream"),
    ("charcoal", "graphite"),
    ("bronze", "copper"),
    ("silver", "platinum"),
    ("ruby", "garnet"),
    ("pearl", "opal"),

    # Emotions & States
    ("joy", "happiness"),
    ("anger", "fury"),
    ("sadness", "sorrow"),
    ("fear", "terror"),
    ("surprise", "shock"),
    ("disgust", "revulsion"),
    ("pride", "arrogance"),
    ("shame", "guilt"),
    ("envy", "jealousy"),
    ("hope", "optimism"),
    ("grief", "mourning"),
    ("anxiety", "worry"),
    ("excitement", "enthusiasm"),
    ("boredom", "apathy"),
    ("confusion", "bewilderment"),

    # Body Parts
    ("elbow", "knee"),
    ("wrist", "ankle"),
    ("thumb", "toe"),
    ("palm", "sole"),
    ("shoulder", "hip"),
    ("forehead", "chin"),
    ("eyebrow", "eyelash"),
    ("nostril", "earlobe"),
    ("bicep", "tricep"),
    ("thigh", "calf"),
    ("heel", "arch"),
    ("knuckle", "joint"),
    ("skull", "cranium"),
    ("spine", "backbone"),
    ("rib", "sternum"),

    # Musical Instruments
    ("banjo", "mandolin"),
    ("violin", "viola"),
    ("trumpet", "trombone"),
    ("flute", "piccolo"),
    ("saxophone", "clarinet"),
    ("drums", "percussion"),
    ("harp", "lyre"),
    ("accordion", "harmonica"),
    ("xylophone", "marimba"),
    ("tambourine", "maracas"),
    ("cello", "bass"),
    ("oboe", "bassoon"),
    ("cymbal", "gong"),
    ("organ", "synthesizer"),
    ("tuba", "euphonium"),

    # Clothing & Accessories
    ("jacket", "blazer"),
    ("sweater", "cardigan"),
    ("pants", "trousers"),
    ("shorts", "bermudas"),
    ("dress", "gown"),
    ("skirt", "kilt"),
    ("shirt", "blouse"),
    ("vest", "waistcoat"),
    ("coat", "overcoat"),
    ("scarf", "shawl"),
    ("gloves", "mittens"),
    ("boots", "shoes"),
    ("sandals", "slippers"),
    ("hat", "cap"),
    ("belt", "sash"),
    ("tie", "bowtie"),
    ("socks", "stockings"),
    ("bracelet", "bangle"),
    ("necklace", "pendant"),
    ("earrings", "studs"),

    # Tools & Equipment
    ("hammer", "mallet"),
    ("screwdriver", "wrench"),
    ("saw", "hacksaw"),
    ("drill", "auger"),
    ("pliers", "pincers"),
    ("chisel", "gouge"),
    ("file", "rasp"),
    ("level", "ruler"),
    ("protractor", "divider"),
    ("shovel", "spade"),
    ("rake", "hoe"),
    ("axe", "hatchet"),
    ("knife", "blade"),
    ("shears", "clippers"),
    ("tweezers", "forceps"),
    ("clamp", "vice"),
    ("ladder", "stepstool"),
    ("bucket", "pail"),
    ("rope", "cord"),
    ("chain", "cable"),

    # Furniture
    ("chair", "stool"),
    ("sofa", "couch"),
    ("table", "desk"),
    ("bed", "cot"),
    ("dresser", "wardrobe"),
    ("shelf", "bookcase"),
    ("bench", "pew"),
    ("ottoman", "footstool"),
    ("cabinet", "cupboard"),
    ("nightstand", "endtable"),
    ("armchair", "recliner"),
    ("chandelier", "sconce"),
    ("mirror", "vanity"),
    ("rug", "carpet"),
    ("drape", "tapestry"),

    # Buildings & Structures
    ("house", "cottage"),
    ("mansion", "estate"),
    ("apartment", "condo"),
    ("fortress", "citadel"),
    ("tower", "spire"),
    ("bridge", "viaduct"),
    ("tunnel", "underpass"),
    ("barn", "shed"),
    ("garage", "carport"),
    ("warehouse", "depot"),
    ("factory", "mill"),
    ("shrine", "sanctuary"),
    ("cathedral", "basilica"),
    ("mosque", "minaret"),
    ("beacon", "lighthouse"),

    # Containers
    ("box", "crate"),
    ("jar", "bottle"),
    ("can", "tin"),
    ("barrel", "keg"),
    ("basket", "hamper"),
    ("bag", "sack"),
    ("pouch", "purse"),
    ("vase", "urn"),
    ("bowl", "dish"),
    ("cup", "mug"),
    ("pitcher", "jug"),
    ("container", "vessel"),
    ("trunk", "chest"),
    ("canister", "caddy"),
    ("flask", "carafe"),

    # Books & Literature
    ("novel", "novella"),
    ("poem", "verse"),
    ("essay", "article"),
    ("biography", "memoir"),
    ("dictionary", "thesaurus"),
    ("atlas", "almanac"),
    ("journal", "diary"),
    ("magazine", "periodical"),
    ("textbook", "manual"),
    ("comic", "manga"),
    ("fable", "parable"),
    ("myth", "legend"),
    ("tale", "story"),
    ("chapter", "section"),
    ("epilogue", "afterword"),

    # School & Education
    ("professor", "instructor"),
    ("student", "pupil"),
    ("classroom", "lecture"),
    ("homework", "assignment"),
    ("exam", "quiz"),
    ("pencil", "pen"),
    ("notebook", "binder"),
    ("eraser", "correction"),
    ("satchel", "briefcase"),
    ("chalkboard", "whiteboard"),
    ("recess", "break"),
    ("grade", "mark"),
    ("diploma", "certificate"),
    ("scholarship", "grant"),
    ("semester", "quarter"),

    # Technology & Computing
    ("computer", "workstation"),
    ("mouse", "trackpad"),
    ("keypad", "numpad"),
    ("monitor", "screen"),
    ("printer", "scanner"),
    ("router", "modem"),
    ("cable", "wire"),
    ("battery", "charger"),
    ("speaker", "headphones"),
    ("microphone", "recorder"),
    ("webcam", "camcorder"),
    ("tablet", "smartphone"),
    ("software", "application"),
    ("website", "webpage"),
    ("browser", "navigator"),
    ("email", "message"),
    ("folder", "directory"),
    ("file", "document"),
    ("server", "database"),
    ("pixel", "resolution"),

    # Medical & Health
    ("physician", "practitioner"),
    ("nurse", "medic"),
    ("clinic", "infirmary"),
    ("medicine", "medication"),
    ("pill", "tablet"),
    ("bandage", "gauze"),
    ("syringe", "needle"),
    ("stethoscope", "thermometer"),
    ("surgery", "operation"),
    ("diagnosis", "prognosis"),
    ("symptom", "ailment"),
    ("vaccine", "immunization"),
    ("prescription", "remedy"),
    ("pharmacy", "drugstore"),
    ("ambulance", "emergency"),

    # Shapes & Geometry
    ("circle", "sphere"),
    ("square", "cube"),
    ("triangle", "pyramid"),
    ("rectangle", "oblong"),
    ("oval", "ellipse"),
    ("hexagon", "octagon"),
    ("pentagon", "heptagon"),
    ("cone", "cylinder"),
    ("prism", "polyhedron"),
    ("angle", "vertex"),
    ("diameter", "radius"),
    ("perimeter", "circumference"),
    ("arc", "curve"),
    ("spiral", "helix"),
    ("rhombus", "diamond"),

    # Art & Creativity
    ("drawing", "sketch"),
    ("sculpture", "statue"),
    ("sketch", "doodle"),
    ("canvas", "easel"),
    ("brush", "palette"),
    ("crayon", "pastel"),
    ("watercolor", "acrylic"),
    ("portrait", "landscape"),
    ("gallery", "exhibition"),
    ("frame", "border"),
    ("artist", "sculptor"),
    ("mural", "fresco"),
    ("mosaic", "collage"),
    ("illustration", "diagram"),
    ("etching", "engraving"),

    # Time & Measurement
    ("second", "moment"),
    ("hour", "period"),
    ("day", "date"),
    ("week", "fortnight"),
    ("month", "season"),
    ("year", "decade"),
    ("century", "millennium"),
    ("dawn", "dusk"),
    ("morning", "evening"),
    ("noon", "midnight"),
    ("twilight", "nightfall"),
    ("yesterday", "tomorrow"),
    ("past", "future"),
    ("stopwatch", "timer"),
    ("calendar", "schedule"),

    # Astronomy & Space
    ("star", "sun"),
    ("planet", "world"),
    ("comet", "asteroid"),
    ("galaxy", "nebula"),
    ("meteor", "meteorite"),
    ("constellation", "zodiac"),
    ("orbit", "rotation"),
    ("occultation", "transit"),
    ("satellite", "spacecraft"),
    ("cosmonaut", "astronomer"),
    ("telescope", "observatory"),
    ("universe", "cosmos"),
    ("crater", "impact"),
    ("gravity", "magnetism"),
    ("vacuum", "void"),

    # Plants & Flora
    ("tree", "shrub"),
    ("flower", "blossom"),
    ("leaf", "petal"),
    ("root", "stem"),
    ("branch", "twig"),
    ("seed", "bulb"),
    ("grass", "lawn"),
    ("vine", "ivy"),
    ("moss", "lichen"),
    ("fern", "bamboo"),
    ("cactus", "succulent"),
    ("rose", "tulip"),
    ("daisy", "sunflower"),
    ("oak", "maple"),
    ("pine", "spruce"),
    ("willow", "birch"),
    ("bush", "hedge"),
    ("garden", "orchard"),
    ("woodland", "timberland"),
    ("meadow", "prairie"),

    # Water & Marine
    ("ocean", "sea"),
    ("lake", "pond"),
    ("river", "stream"),
    ("creek", "brook"),
    ("cascade", "rapids"),
    ("wave", "ripple"),
    ("tide", "current"),
    ("shore", "coast"),
    ("sandbar", "shoal"),
    ("island", "atoll"),
    ("reef", "coral"),
    ("bay", "cove"),
    ("harbor", "port"),
    ("dock", "pier"),
    ("whirlpool", "eddy"),

    # Landforms & Geography
    ("hill", "knoll"),
    ("valley", "gorge"),
    ("cliff", "bluff"),
    ("cave", "cavern"),
    ("peak", "summit"),
    ("plateau", "mesa"),
    ("dune", "sandhill"),
    ("glacier", "iceberg"),
    ("crater", "caldera"),
    ("peninsula", "cape"),
    ("delta", "estuary"),
    ("plain", "flatland"),
    ("swamp", "marsh"),
    ("rainforest", "tropics"),
    ("tundra", "steppe"),

    # Fabrics & Materials
    ("cotton", "linen"),
    ("silk", "satin"),
    ("wool", "fleece"),
    ("leather", "suede"),
    ("denim", "canvas"),
    ("velvet", "velour"),
    ("nylon", "polyester"),
    ("plastic", "polymer"),
    ("metal", "alloy"),
    ("wood", "timber"),
    ("stone", "marble"),
    ("glass", "crystal"),
    ("ceramic", "porcelain"),
    ("rubber", "latex"),
    ("paper", "cardboard"),

    # Weapons & Combat
    ("sword", "saber"),
    ("dagger", "dirk"),
    ("spear", "lance"),
    ("bow", "crossbow"),
    ("arrow", "bolt"),
    ("shield", "buckler"),
    ("armor", "chainmail"),
    ("cannon", "artillery"),
    ("rifle", "musket"),
    ("pistol", "revolver"),

    # Jewelry & Gems
    ("diamond", "crystal"),
    ("sapphire", "topaz"),
    ("amethyst", "quartz"),
    ("ring", "band"),
    ("crown", "tiara"),
    ("brooch", "pin"),
    ("charm", "trinket"),
    ("locket", "medallion"),
    ("jewel", "gemstone"),
    ("gold", "platinum"),

    # Celebrations & Events
    ("party", "celebration"),
    ("wedding", "marriage"),
    ("birthday", "anniversary"),
    ("festival", "carnival"),
    ("parade", "procession"),
    ("ceremony", "ritual"),
    ("banquet", "feast"),
    ("concert", "recital"),
    ("graduation", "commencement"),
    ("reunion", "gathering"),

    # Miscellaneous
    ("king", "emperor"),
    ("queen", "empress"),
    ("prince", "duke"),
    ("wizard", "sorcerer"),
    ("knight", "paladin"),
    ("dragon", "wyvern"),
    ("treasure", "fortune"),
    ("magic", "sorcery"),
    ("potion", "elixir"),
    ("spell", "enchantment"),
]
